BEGIN TRANSACTION ;
CREATE SEQUENCE public.userid
    INCREMENT 1
    START 0
    MINVALUE 0
    MAXVALUE 5321213
    CACHE 1;

ALTER SEQUENCE public.userid
    OWNER TO postgres;
COMMIT;

BEGIN TRANSACTION ;
CREATE SEQUENCE public.postid
    INCREMENT 1
    START 1
    MINVALUE 0
    MAXVALUE 213123
    CACHE 1;

ALTER SEQUENCE public.postid OWNER TO postgres;
COMMIT;